title: inviato
email: inviato.co@gmail.com
description: A trading company.
url: "https://inviato.us"
markdown: kramdown

# exclude (default):
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
